### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by egarson** [vincentdoerig/vue3-typescript-tailwind-starter#2]
Doing a git clone, npm install and then 'npm run build' emits:

$ npm run build

> vue3-ts-tailwind-starter@0.0.0 build
> vite build

building for production...
[vite:css] Loading PostCSS Plugin failed: Package subpath './lib/node' is not defined by "exports" in /codex/vue3-typescript-tailwind-starter/node_modules/postcss/package.json
[snip more errors]

I am on npm 8.4.1....

**Comment by vincentdoerig** [comment]
Hey there, sorry about that. I upgraded all dependencies (d47cf266a7f4a2acd998e4a9aac9854494a93a04) and it is working for me now. Feel free to reopen if the issue persists.

**Comment by egarson** [comment]
No worries at all. Many thanks for fixing this!
